overpass/routes/archive.py
from typing import Any, Text

from flask import Blueprint, abort, redirect, url_for
from flask.templating import render_template
from flask.wrappers import Response
from flask_discord import Unauthorized, requires_authorization
from overpass import discord
from overpass.archive import get_archived_streams, serve_file
from overpass.db import query_one

bp = Blueprint("archive", __name__)


@bp.errorhandler(Unauthorized)
def redirect_discord_unauthorized(e) -> Any:
    return redirect(url_for("auth.login"))


@bp.before_request
@requires_authorization
def require_auth() -> None:
    pass


@bp.route("/")
def list_archived_streams() -> Text:
    """List publically archived streams.

    Returns:
        Text: Static page rendered by Flask.
    """
    archive = get_archived_streams()
    return render_template("archive.html", archive=archive)


@bp.route("/download/<unique_id>")
def serve_archive(unique_id: str) -> Response:
    """Serves stream from the archive.

    Args:
        unique_id (str): The stream's unique ID.

    Returns:
        Response: File being served by Flask's Response class.
    """
    user = discord.fetch_user()
    stream = query_one(
        """
        SELECT * FROM stream
        WHERE archived_file IS NOT NULL
        AND unique_id = ?
        """,
        [unique_id],
    )
    if user.id == stream["user_snowflake"]:
        # The user requesting the stream created it.
        # Therefore they shall always have access to the file.
        return serve_file(stream)
    elif bool(stream["archivable"]):
        # The stream is publically archived.
        return serve_file(stream)
    else:
        # The stream does not exist.
        return abort(404)

overpass/routes/auth.py
from typing import Any, Text

from flask import Blueprint, abort, current_app, redirect, session, url_for
from flask.templating import render_template
from flask_discord import RateLimited, Unauthorized
from overpass import discord
from overpass.auth import (
    DISCORD_GUILD_ID,
    add_user,
    check_if_user_exists,
    update_login_time,
    verify,
)

auth = Blueprint("auth", __name__)


@auth.route("/login/")
def login() -> Any:
    """Redirect user to Discord's SSO page

    Returns:
        Any: Redirection to Discord's SSO page
    """
    return discord.create_session(scope=["identify", "guilds"])


@auth.route("/logout/")
def logout() -> Text:
    """Revoke a user's session

    Returns:
        Text: Flask rendered template
    """
    discord.revoke()
    return render_template("alert.html", info="You've been logged out.")


@auth.route("/callback/")
def callback() -> Any:
    """Callback endpoint for SSO service

    Returns:
        Any: Redirect to home page if everything went well, else return 401.
    """
    try:
        discord.callback()
        user = discord.fetch_user()
        if DISCORD_GUILD_ID:
            if not verify():
                # When the callback succeeds, the token for the user gets
                # set in memory
                # Since the user isn't a member of the guild
                # we reset the session to prevent access to the API
                current_app.logger.error(
                    f"Username {user.username} with ID {user.id} is not a member of the target guild"  # noqa: E501
                )
                session.clear()
                return abort(401)

        # Assume successful login
        if not check_if_user_exists(user.id):
            add_user(user.username, user.id, user.avatar_url)
        else:
            current_app.logger.info(f"User {user.username} has just signed in")
            # Update last login time
            update_login_time(user.id)

        return redirect(url_for("index.home"))
    except RateLimited:
        return "We are currently being rate limited, try again later."


@auth.errorhandler(Unauthorized)
def redirect_discord_unauthorized(e) -> Any:
    return redirect(url_for("auth.login"))


# Runs when abort(401) is called.
@auth.errorhandler(401)
def redirect_unauthorized(e) -> Any:
    return """
    <h2>Your Discord user is not authorized to use this application.</h2>
    <p>Please verify that you are a member of the target Discord server.</p>
    """

overpass/routes/hls.py
from os import environ
from typing import Any

from flask import Blueprint, abort, redirect, send_from_directory, url_for
from flask.helpers import send_file
from flask_discord import Unauthorized, requires_authorization
from overpass.db import query_one
from overpass.stream_utils import (
    get_stream_key_from_unique_id,
    rewrite_stream_playlist,
)
from requests.sessions import Request

bp = Blueprint("hls", __name__)


@bp.errorhandler(Unauthorized)
def redirect_discord_unauthorized(e):
    return redirect(url_for("auth.login"))


@bp.before_request
@requires_authorization
def require_auth() -> None:
    pass


@bp.after_request
def disable_cache(r: Request):
    # https://stackoverflow.com/questions/31918035/javascript-only-works-after-opening-developer-tools-in-chrome
    # Finally fixed the HLS buffer issue...
    r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    return r


@bp.route("/<unique_id>/<file>")
def serve_stream(unique_id: str, file: str) -> Any:
    """Serve stream via its unique ID

    Example:
    A stream uses the following IDs and keys:
    Stream key = 1451fgsa
    Unique ID = klzfls156

    GET /watch/klzfls156/index.m3u8
    < HLS_DIR/1451fgsa-index.m3u8

    GET /watch/klzfls156/1.ts
    < HLS_DIR/1451fgsa-1.ts

    Args:
        unique_id (str): The stream's unique ID
        file (str): The requested file

    Returns:
        Any: Serves file from HLS path if exists.
    """
    stream_key = get_stream_key_from_unique_id(unique_id)
    stream = query_one(
        "SELECT end_date FROM stream WHERE stream_key = ?", [stream_key]
    )
    if stream_key and not stream["end_date"]:
        if file == "index.m3u8":
            try:
                playlist = rewrite_stream_playlist(stream_key)
                return send_file(playlist, mimetype="application/x-mpegURL")
            except FileNotFoundError:
                return abort(404)
        else:
            return send_from_directory(
                environ.get("HLS_PATH"), f"{stream_key}-{file}"
            )

    return abort(404)

overpass/routes/manage_user.py
from typing import Text

from flask import Blueprint, redirect, url_for
from flask.templating import render_template
from flask_discord import Unauthorized, requires_authorization
from overpass import discord
from overpass.db import query_many, query_one

bp = Blueprint("manage", __name__)


@bp.errorhandler(Unauthorized)
def redirect_discord_unauthorized(e):
    return redirect(url_for("auth.login"))


@bp.before_request
@requires_authorization
def require_auth():
    pass


@bp.route("/me")
def me() -> Text:
    """Render a page to manage stream properties

    Returns:
        Text: Static page rendered by Flask.
    """
    discord_user = discord.fetch_user()
    user = query_one(
        "SELECT * FROM user WHERE snowflake = ?", [discord_user.id]
    )
    streams = query_many(
        "SELECT * FROM stream WHERE user_snowflake = ?", [discord_user.id]
    )
    if streams:
        for stream in streams:
            try:
                duration = stream["end_date"] - stream["start_date"]
                stream["duration"] = str(duration)
            except TypeError:
                continue
            stream["username"] = user["username"]
        return render_template("manage_user.html", user=user, streams=streams)

    return render_template("manage_user.html", user=user)

overpass/routes/stream.py
import uuid
from os import environ
from typing import Any

from flask import Blueprint, abort, redirect, request, url_for
from flask.templating import render_template
from flask_discord import Unauthorized, requires_authorization
from overpass import discord
from overpass.db import query_one
from overpass.forms import StreamGenerationForm
from overpass.stream_api import add_stream_to_db, update_db_fields

bp = Blueprint("stream", __name__)


@bp.errorhandler(Unauthorized)
def redirect_discord_unauthorized(e) -> Any:
    return redirect(url_for("auth.login"))


@bp.before_request
@requires_authorization
def require_auth() -> None:
    pass


@bp.route("/manage/<unique_id>", methods=["GET", "POST"])
def manage_stream(unique_id: str) -> Any:
    """Manage a stream's properties via its unique ID.

    Args:
        unique_id (str): The stream's unique ID.

    Returns:
        Any: A static page rendered by Flask.
    """
    user = discord.fetch_user()
    form = StreamGenerationForm()
    stream = query_one(
        """SELECT title,
        description,
        category,
        archivable,
        unlisted,
        user_snowflake
        FROM stream
        WHERE unique_id = ?
        """,
        [unique_id],
    )

    if not stream:
        return render_template("alert.html", error="Invalid stream ID."), 404

    # Populate the stream editing form.
    form.title.data = stream["title"]
    form.description.data = stream["description"]
    form.category.data = stream["category"]
    form.archivable.data = stream["archivable"]
    form.unlisted.data = stream["unlisted"]

    if stream["user_snowflake"] == user.id:
        if request.method == "GET":
            return render_template(
                "manage_stream.html", form=form, unique_id=unique_id
            )

        if request.method == "POST":
            form = StreamGenerationForm(request.form)
            if form.validate():
                keys_to_change = {}
                for key, value in form.data.items():
                    if stream[key] != value:
                        keys_to_change[key] = value
                update_db_fields(unique_id, **keys_to_change)
                return render_template(
                    "manage_stream.html",
                    form=form,
                    unique_id=unique_id,
                    update=True,
                )
    else:
        # User does not have access to manage this stream ID.
        return abort(403)


@bp.route("/generate", methods=["GET", "POST"])
def generate_stream_key() -> Any:
    form = StreamGenerationForm(request.form)
    server = f"rtmp://{environ.get('RTMP_SERVER')}"
    if request.method == "GET":
        return render_template(
            "generate_stream.html", form=form, server=server
        )
    else:
        user = discord.fetch_user()
        snowflake = user.id

        keyvar = uuid.uuid4()
        stream_key = str(keyvar)[0:8]
        unique_id = str(keyvar)[24:32]

        if form.validate():
            title = form.title.data
            description = form.description.data
            category = form.category.data
            archivable = form.archivable.data
            unlisted = form.unlisted.data

            add_stream_to_db(
                snowflake,
                title,
                description,
                category,
                archivable,
                unique_id,
                stream_key,
                unlisted,
            )

            return render_template(
                "generate_stream.html",
                form=form,
                user=user,
                key=stream_key,
                id=unique_id,
                unlisted=unlisted,
                server=server,
            )

overpass/routes/watch.py
from typing import Any, Union

from flask import Blueprint, redirect, render_template, url_for
from flask_discord import Unauthorized, requires_authorization
from overpass import discord
from overpass.stream_utils import (
    get_livestreams_by_username,
    get_unlisted_livestreams_by_username,
)
from overpass.watch import get_single_archived_stream, return_stream_page

bp = Blueprint("watch", __name__)


@bp.errorhandler(Unauthorized)
def redirect_discord_unauthorized(e) -> Any:
    return redirect(url_for("auth.login"))


@bp.before_request
@requires_authorization
def require_auth() -> None:
    pass


@bp.route("/<username>")
@bp.route("/<username>/<unique_id>")
def watch_stream(username: str, unique_id: Union[str, None] = None) -> Any:
    """Generates a page to watch streams with.

    Args:
        username (str): The user whose stream to watch
        unique_id (Union[str, None], optional): The unique ID of a stream.
        This is only set if the stream is either private, or archived.
        Defaults to None.

    Returns:
        Any: Static page rendered by Flask.
    """
    stream = get_livestreams_by_username(username)
    if stream and not unique_id:
        # Regular livestream
        return render_template("watch.html", live=True, stream=stream)

    if unique_id:
        # Lets first check if its an unlisted stream
        unlisted = get_unlisted_livestreams_by_username(username)
        if unlisted:
            # Unlisted stream
            return render_template("watch.html", live=True, stream=unlisted)

        # It's an archived stream at this point
        try:
            stream = get_single_archived_stream(unique_id)
            return return_stream_page(unique_id, stream)
        except StopIteration:
            pass

        # Unlisted and archived
        try:
            stream = get_single_archived_stream(
                unique_id, all_metadata=True, private=True
            )
            if bool(stream["archivable"]) and bool(stream["unlisted"]):
                return return_stream_page(unique_id, stream)
        except StopIteration:
            pass

        # Private stream
        try:
            user = discord.fetch_user()
            stream = get_single_archived_stream(unique_id, private=True)
            if stream["user_snowflake"] == user.id:
                return return_stream_page(unique_id, stream)
            else:
                return render_template(
                    "alert.html", error="Invalid stream key."
                )
        except StopIteration:
            # The stream ID doesn't exist at all at this point
            return (
                render_template("alert.html", error="Invalid stream key."),
                404,
            )

    return render_template("watch.html")

overpass/templates/alert.html
{% extends "layout.html" %}

{% block title %}
Alert
{% endblock %}

{% block content %}
{% include "header.html" %}
{% if error %}
<div class="m-3 alert alert-danger" role="alert">
  {{error}}
</div>
{% endif %}
{% if info %}
<div class="m-3 alert alert-info" role="alert">
  {{info}}
</div>
{% endif %}
{% endblock %}

overpass/templates/archive.html
{% extends "layout.html" %}
{% block title %}
Archive
{% endblock %}
{% block content %}
{% include "header.html" %}
<h5>Archive</h5>
{% if archive is defined and archive|length %}
  <table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">User</th>
      <th scope="col">Title</th>
      <th scope="col">Duration</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for stream in archive %}
    <tr>
      <th scope="row">{{ stream['start_date'] }} UTC</th>
      <td>{{ stream['username'] }}</td>
      <td>{{ stream['title'] }}</td>
      <td>{{ stream["duration"] }}</td>
      <td>
        <div class="d-flex">
          <a class="mx-1 text-decoration-none btn-sm btn-dark" href="{{url_for('watch.watch_stream', username=stream['username'], unique_id=stream['unique_id'])}}"><i class="fas fa-play-circle"></i> Play</a>
          <a class="mx-1 text-decoration-none btn-sm btn-dark" data-bs-toggle="collapse" href="#description-{{ loop.index }}" role="button" aria-expanded="false" aria-controls="description-{{ loop.index }}"><i class="fas fa-caret-down fa-lg"></i> Details</a>
        </div>
      </td>
    </tr>
    <tr>
      <th scope="row" colspan=4>
        <div class="collapse" id="description-{{ loop.index }}">
            <div class="card card-body" style="font-weight: normal">
              {{ stream["description"] | nl2br }}
            </div>
        </div>
      </th>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-primary" role="alert">
   There are no streams in the archive yet.
</div>
{% endif %}
{% endblock %}

overpass/templates/generate_stream.html
{% extends "layout.html" %}
{% block title %}
Go Live
{% endblock %}
{% block content %}
{% include "header.html" %}
<div class="alert alert-primary" role="alert">
  Streaming server: <b>{{ server }}</b>
</div>
<form method="post" action="{{url_for('stream.generate_stream_key')}}">
    <!-- Perhaps we should use WTForms instead. -->
    <div class="my-3 form-group">
        {{ form.title(class="form-control", placeholder="Title") }}
    </div>
    <div class="my-3 form-group">
        {{ form.category(class="form-control", placeholder="Category") }}
    </div>
    <div class="my-3 form-group">
        {{ form.description(class="form-control", placeholder="Description") }}
    </div>
    <div class="m-2 form-check">
        {{ form.archivable.label }}
        {{ form.archivable(class="form-check-input") }}
    </div>
    <div class="m-2 form-check">
        {{ form.unlisted.label }}
        {{ form.unlisted(class="form-check-input") }}
    </div>
    <button type="submit" class="btn btn-dark"><i class="fas fa-key"></i> Generate stream key</button>
</form>
{% if key %}
<div class="alert alert-success" role="alert">
Stream key: <b>{{ key }}</b>
</div>
{% endif %}
{% if unlisted %}
<div class="alert alert-info" role="alert">
  Your unlisted stream will be available <a href="{{url_for('watch.watch_stream', username=user.username, unique_id=id)}}" class="alert-link">here</a>.
</div>
{% endif %}
{% endblock %}

overpass/templates/header.html
<div id="header">
    <nav class="mb-3 navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('index.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('archive.list_archived_streams')}}">Archive</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('stream.generate_stream_key')}}"><b>Go Live</b></a>
                    </li>
                </ul>
                <form class="m-2 d-flex">
                    <a href="{{url_for('manage.me')}}" class="me-2 btn btn-outline-dark"><i class="fas fa-user"></i> My Profile</a>
                    <a href="{{url_for('auth.logout')}}" class="btn btn-outline-dark"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                </form>
            </div>
        </div>
    </nav>
</div>

overpass/templates/index.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}

{% block meta %}
    <meta http-equiv="refresh" content="15">
{% endblock %}


{% block content %}
{% if authorized %}
{% include "header.html" %}
{% if streams is defined and streams|length %}
{% for stream in streams %}
<div class="m-3 card">
  <div class="card-header">
    <b>{{stream['username']}}</b> is streaming!
  </div>
  <div class="card-body">
    <h5 class="card-title">{{stream['title']}}</h5>
    <p class="card-text">{{stream['description']}}</p>
    <a href="{{url_for('watch.watch_stream', username=stream['username'])}}" class="btn btn-dark"><i class="fas fa-play-circle"></i> Play</a>
  </div>
</div>
  {% endfor %}
  {% else %}
  <div class="alert alert-primary" role="alert">
    No one is streaming at the moment. Would you like to <a href="{{url_for('stream.generate_stream_key')}}"
      class="alert-link">go live?</a>
  </div>
  {% endif %}
  {% else %}
  <div class="card text-center">
    <div class="card-header">
      Overpass
    </div>
    <div class="card-body">
      <h5 class="card-title">Sign in</h5>
      <p class="card-text">Click the button to sign in with Discord. <br>
        <br>
        <a href={{url_for('auth.login')}}><img src={{url_for('static', filename="sign_in_with_discord_small.png")}}
            class="img-fluid" /></a>
    </div>
  </div>
  {% endif %}
  {% endblock %}

overpass/templates/layout.html
<html>
<head>
    <title>{% block title %}{% endblock %} - Overpass</title>
    {% block meta %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
</head>

<body>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <div class="pt-3 container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

overpass/templates/manage_stream.html
{% extends "layout.html" %}
{% block title %}
Edit Stream
{% endblock %}

{% block content %}
{% include "header.html" %}
{% if update %}
<div class="alert alert-success" role="alert">
Stream settings updated.
</div>
{% endif %}
<form method="post" action="{{url_for('stream.manage_stream', unique_id=unique_id)}}">
    <div class="m-2 form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
    </div>
    <div class="m-2 form-group">
        {{ form.category.label }}
        {{ form.category(class="form-control") }}
    </div>
    <div class="m-2 form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control") }}
    </div>
    <div class="m-2 form-check">
        {{ form.archivable.label }}
        {{ form.archivable(class="form-check-input") }}
    </div>
    <div class="m-2 form-check">
        {{ form.unlisted.label }}
        {{ form.unlisted(class="form-check-input") }}
    </div>
    <button type="submit" class="btn btn-dark"><i class="fas fa-check-circle"></i> Apply Changes</button>
</form>
{% endblock %}

overpass/templates/manage_user.html
{% extends "layout.html" %}
{% block title %}
Manage Profile
{% endblock %}

{% block content %}
{% include 'header.html' %}
<h4>User Info</h4>
<div class="mb-4 card">
  <div class="card-body ">
    <div class="container">
      <div class="row">
        {% if user['avatar'] %}
        <div class="col-md-auto">
         <img src={{user['avatar']}} class="img-fluid" />
        </div>
        {% endif %}
        <div class="col-sm">
          <h5 class="card-title">{{user['username']}}</h5>
          <p class="mb-0 card-text">Last login date: {{user['last_login_date']}} UTC</p>
          <p class="mb-0 card-text">Discord User ID: {{user['snowflake']}}</p>
        </div>
      </div>
  </div>
  </div>
</div>
{% if streams is defined %}
<h5>My streams</h5>
  <table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Title</th>
      <th scope="col">Duration</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for stream in streams %}
    <tr>
      {% if stream['start_date'] %}
      <th scope="row">{{ stream['start_date'] }} UTC</th>
      {% else %}
      <th scope="row">Not Started Yet</th>
      {% endif %}
      <td>{{ stream['title'] }}</td>
      {% if stream["duration"] %}
      <td>{{ stream['duration'] }}</td>
      {% else %}
      <td><b>N/A</b></td>
      {% endif %}
      <td>
        <div class="d-flex flex-wrap">
        <!-- Bottom border is set here due to wrapping on small viewports -->
          {% if not stream["duration"] and stream["start_date"] %}
          <span class="me-1 mb-1 badge bg-danger">LIVE</span>
          {% endif %}
          {% if stream["archivable"] %}
          <span class="me-1 mb-1 badge bg-dark">Archived</span>
          {% else %}
          <span class="me-1 mb-1 badge bg-secondary">Not Archived</span>
          {% endif %}
          {% if stream["unlisted"] %}
          <span class="me-1 mb-1 badge bg-dark">Unlisted</span>
          {% endif %}
        </div>
      </td>
      <td>
        <div class="d-inline-flex">
          <a class="mx-1 text-decoration-none btn-sm btn-dark" href="{{url_for('stream.manage_stream', unique_id=stream['unique_id'])}}"><i class="fas fa-pen"></i> Edit Stream</a>
          {% if not stream["duration"] and not stream["unlisted"] %}
          <a class="mx-1 text-decoration-none btn-sm btn-dark" href="{{url_for('watch.watch_stream', username=user['username'])}}"><i class="fas fa-play-circle"></i> Play</a>
          {% else %}
          <a class="mx-1 text-decoration-none btn-sm btn-dark" href="{{url_for('watch.watch_stream', username=user['username'], unique_id=stream['unique_id'])}}"><i class="fas fa-play-circle"></i> Play</a>
          {% endif %}
          <a class="mx-1 text-decoration-none btn-sm btn-dark" data-bs-toggle="collapse" href="#description-{{ loop.index }}" role="button" aria-expanded="false" aria-controls="description-{{ loop.index }}"><i class="fas fa-caret-down fa-lg"></i> Details</a>
        </div>
      </td>
    </tr>
    <tr>
      <th scope="row" colspan=4>
        <div class="collapse" id="description-{{ loop.index }}">
            <div class="card card-body" style="font-weight: normal">
              {{ stream["description"] | nl2br }}
              <div class="d-flex">
                <span class="me-1 mb-1 badge bg-dark">Stream Key: {{ stream["stream_key"] }}</span>
                <span class="me-1 mb-1 badge bg-dark">Unique ID: {{ stream["unique_id"] }}</span>
              </div>
            </div>
        </div>
      </th>
    </tr>
  {% endfor %}
  </tbody>
</table>
  {% endif %}
{% endblock %}

overpass/templates/watch.html
{% extends "layout.html" %}


{% block title %}
Watch
{% endblock %}

{% block content %}
{% include "header.html" %}
<script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>
<link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />

{% if stream %}
<div id="container">
      <video
        id="my-video"
        class="video-js vjs-big-play-centered"
        controls
        preload="auto"
        width="768"
        height="432"
      >
  {% if live %}
      <source src="{{url_for('hls.serve_stream', unique_id=stream['unique_id'], file='index.m3u8')}}" type="application/x-mpegURL" />
      </video>
  {% else %}
      <source src="{{archive_link}}" type="video/mp4" />
      </video>
  {% endif %}
    <script>
      // Disable right-clicking in the video frame
      var myVideo = document.getElementById("my-video");
      if (myVideo.addEventListener) {
          myVideo.addEventListener('contextmenu', function(e) {
              e.preventDefault();
          }, false);
      } else {
          myVideo.attachEvent('oncontextmenu', function() {
              window.event.returnValue = false;
          });
      }
      var player = videojs('my-video', {
      responsive: true,
      fluid: true
      });
      player.play();
    </script>
  <div id="container">
      <br>
      <h3>{{stream['title']}}</h3>
      <h5>by {{stream['username']}}</h5>
      <div class="mb-2 card">
          <div class="card-body">
              {{stream['description'] | nl2br}}
          </div>
      </div>
  </div>
</div>
{% else %}
<div class="alert alert-danger" role="alert">
  The user is offline.
</div>
{% endif %}
{% endblock %}